In [13]:
import numpy as np

# NUMPY

In [14]:
array = np.array([1,2,3])
print(array)

[1 2 3]


## shape

In [15]:
array.shape

(3,)

## reshape

In [16]:
array2 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
x = array2.reshape(3,5)

## ndim, 
## dtype.name, 
## size,
## type

In [17]:
print("shape: ",x.shape) 

print("dimension: ",x.ndim) #matris boyutu
                            
print("data type: ",x.dtype.name) 

print("size: ",x.size) #reshape'ten önceki boyut
                       
                       
print("type",type(x))

shape:  (3, 5)
dimension:  2
data type:  int32
size:  15
type <class 'numpy.ndarray'>


In [18]:
array3 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
array3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [19]:
print(array3.shape)

(3, 5)


# ... Zeros

In [22]:
zeros = np.zeros((3,4))
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [21]:
zeros[0,0] = 5
print(zeros)

[[5. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [23]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
np.empty((4,5))   #bos array

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.06811490e-306, 1.89146896e-307],
       [7.56571288e-307, 4.00544531e-307, 1.11261095e-306,
        3.56043054e-307, 1.37961641e-306],
       [2.22518251e-306, 1.33511969e-306, 1.69118108e-306,
        8.06632139e-308, 1.20160711e-306],
       [1.69119330e-306, 1.78019082e-306, 1.11261570e-306,
        2.31423435e-306, 8.34454474e-308]])

In [26]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [27]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

### Numpy Basic Operations
##### Boyutlar aynı olmalı !!!

In [28]:
x = np.array([10,20,30])
y = np.array([40,50,60])

print(x + y)
print(x - y)
print(x * y)

[50 70 90]
[-30 -30 -30]
[ 400 1000 1800]


...

In [31]:
liste = [1,2,3,4]
array = np.array([5,6,7,8])
print(f"List: {liste}")
print(f"Array: {array}")

List: [1, 2, 3, 4]
Array: [5 6 7 8]


In [32]:
array = np.array(liste)
print(array)

[1 2 3 4]


In [33]:
liste2 = list(array)
print(liste2)

[1, 2, 3, 4]


...

In [40]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [41]:
b = a
c = a
b[0] = 9
print(a,b,c)

[9 2 3] [9 2 3] [9 2 3]


###### *** a,b,c için memory'de aynı alan ayrıldığı için( np.array'den kaynaklı) birisinde değer değişince hepsinde değişti
###### bu olayı copy() metodu ile halledebiliriz.

In [45]:
d = a.copy()

....

In [46]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(a)

[1 2 3 4 5 6 7 8 9]


In [47]:
print(a[::-1])

[9 8 7 6 5 4 3 2 1]


In [49]:
print(a[:4])

[1 2 3 4]


In [52]:
print(a[4:])

[5 6 7 8 9]


### ...

In [54]:
b = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [55]:
print(b[1,1])

7


In [60]:
print(b[0:4,:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [58]:
print(b[:,:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [59]:
print(b[-1,:])

[ 6  7  8  9 10]


In [62]:
print(b[0,:])

[1 2 3 4 5]


....

In [64]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [65]:
a = array.ravel() #3x3 lük matrisi tek boyutlu yapar.
print(a)

[1 2 3 4 5 6 7 8 9]


In [67]:
array2 = a.reshape(3,3) #tek boyutlu matrisi 3x3 boyutlu yapar.
print(array2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [69]:
#Transpose
print(array2.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [74]:
#resize
array3 = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
print(array3)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [82]:
array3.resize((2,5))
print(array3)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [81]:
### Resize vs Reshape

In [83]:
# Resize, ile yapılan boyut degisikliliği kalıcıdır, aynı array'in içine kaydeder.
# Reshape, ile yapılan değişimler kalıcı değildir. Yapılan değişim başka bir değişkene kaydedilmelidir.